import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { API_URL, API_URI } from '../app.constants';

@Injectable({
  providedIn: 'root'
})
export class SignUpService {

  constructor(
    private http : HttpClient
  ) { }

  /**
   * This is the method that will sign a user up.  It will send a POST call
   * to the API.  Then it will send back the generated observable.
   * 
   * @param username The username supplied by the user on the signup page.
   * @param password The password supplied by the user on the signup page.
   * @returns The observable generated by the POST request.
   */
  signup(username, password) {    
    // Set up the URL    
    let url = `${API_URL}${API_URI}/users/sign-up`;
    // Build the body of the POST request
    let body = { username : username, password : password };
    // Send back the observable
    return this.http.post(url, body);    
  }  // End of the 'signup' mehtod

}  // End of the 'SignUpService' classs
